In [3]:
import numpy as np

marks = np.array([
    [78, 85, 92],   # priya
    [65, 72, 68],   # rahul
    [90, 88, 95],   # sneha
    [55, 60, 58]    # amit
])

students = ["priya", "rahul", "sneha", "amit"]
subjects = ["maths", "english", "science"]

print("marks table")
print("-" * 30)
print(marks)
print("-" * 30)

print("shape:", marks.shape)   # 4 rows, 3 columns
print("total elements:", marks.size)

print("-" * 30)

print("student totals:")
for i in range(len(students)):
    total = np.sum(marks[i])
    avg = round(np.mean(marks[i]), 1)
    print(students[i], "-> total:", total, "avg:", avg)

print("-" * 30)
print("subject averages:")
for i in range(len(subjects)):
    avg = round(np.mean(marks[:, i]), 1)
    print(subjects[i], "->", avg)

marks table
------------------------------
[[78 85 92]
 [65 72 68]
 [90 88 95]
 [55 60 58]]
------------------------------
shape: (4, 3)
total elements: 12
------------------------------
student totals:
priya -> total: 255 avg: 85.0
rahul -> total: 205 avg: 68.3
sneha -> total: 273 avg: 91.0
amit -> total: 173 avg: 57.7
------------------------------
subject averages:
maths -> 72.0
english -> 76.2
science -> 78.2
