In [1]:
import numpy as np

# Creating matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)


# Addition
addition = A + B
print("\nMatrix Addition:")
print(addition)


# Matrix Multiplication
multiplication = np.dot(A, B)
print("\nMatrix Multiplication:")
print(multiplication)


# Transpose
transpose = A.T
print("\nTranspose of Matrix A:")
print(transpose)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix Addition:
[[ 6  8]
 [10 12]]

Matrix Multiplication:
[[19 22]
 [43 50]]

Transpose of Matrix A:
[[1 3]
 [2 4]]
