In [4]:
import numpy as np


A = np.array([[1,2],
              [3,4],
              [5,6]])


print("Original Matrix:")
print(A)


# SVD

U, S, VT = np.linalg.svd(A)


print("\nMatrix U:")
print(U)


print("\nSingular Values:")
print(S)


print("\nMatrix VT:")
print(VT)

Original Matrix:
[[1 2]
 [3 4]
 [5 6]]

Matrix U:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

Singular Values:
[9.52551809 0.51430058]

Matrix VT:
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
