In [7]:
import numpy as np


def gram_schmidt(vectors):

    orthogonal_vectors = []

    for v in vectors:

        u = v.copy().astype(float)

        for prev in orthogonal_vectors:
            projection = (
                np.dot(v, prev) /
                np.dot(prev, prev)
            ) * prev

            u = u - projection

        orthogonal_vectors.append(u)

    return orthogonal_vectors



# Input vectors

vectors = [
    np.array([1, 1, 0]),
    np.array([1, 0, 1]),
    np.array([0, 1, 1])
]


result = gram_schmidt(vectors)


print("Original Vectors:")
for v in vectors:
    print(v)


print("\nOrthogonal Vectors:")
for v in result:
    print(v)


print("\nNormalized Orthogonal Vectors:")

for v in result:
    print(v / np.linalg.norm(v))

Original Vectors:
[1 1 0]
[1 0 1]
[0 1 1]

Orthogonal Vectors:
[1. 1. 0.]
[ 0.5 -0.5  1. ]
[-0.66666667  0.66666667  0.66666667]

Normalized Orthogonal Vectors:
[0.70710678 0.70710678 0.        ]
[ 0.40824829 -0.40824829  0.81649658]
[-0.57735027  0.57735027  0.57735027]
